name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.33
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/requirements =/requirements = python3,kivy/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
