name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install buildozer
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/requirements =/requirements = python3,kivy/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
